spring:
  application:
    name: spring-web-basic
  cloud:
    aws:
      credentials:
        accessKey: ${AWS_S3_ACCESS_KEY}
        secretKey: ${AWS_S3_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: s3-bucket-practice9874

   #기본프로필 (로컬 개발용)
  datasource:
    url: jdbc:postgresql://myapp-postgres-db.ct0w2msg4t9k.ap-northeast-2.rds.amazonaws.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}

server:
  port: 8080






springdoc:
  swagger-ui:
    path: /api-docs-ui.html #ui페이지 경로
    tags-sorter: alpha #태그정렬방식 알파뱃순
    operations-sorter: method #매소드도 정리해준다 기본값 알파뱃순 포스트맨아래로
    display-request-duration: true #요청에 소요된 시간 표시
    doc-expansion: list #문서 펼침상태 (none, list,full)




  api-docs:
    path: /my-api  #swagger가 우리 api의 정보를 얻어오기 위해서 요청하는 Url

logging:
  level:
    com.codeit.springwebbasic.common.log.LogExample: debug
    org.springframework.web: trace

  file:
    name: C:\springs\logs\spring-web-basic\app.logs


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics


---
#docker 환경용 프로플
#스프링 초기화 시 만약 프로필 active가 docker라면 아래설정을 우선시 하겠다
spring:
  config:
    activate:
      on-profile: docker

 #환경 변수로 외부에서 주입을 받겠다 노출시키지않겠다
#위에 것은 다 그대로고 바꾸고싶은거만 여기다

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}